# Generated by Django 3.2.6 on 2021-08-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_1',
        ),
        migrations.AddField(
            model_name='post',
            name='main_image',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_2',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_3',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_4',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_5',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
    ]
